package jp.tokyo.higashimurayama.tohnaman.batch.mybatis.mapper;

import java.util.List;
import jp.tokyo.higashimurayama.tohnaman.batch.mybatis.model.MstAddress;
import jp.tokyo.higashimurayama.tohnaman.batch.mybatis.model.MstAddressExample;
import org.apache.ibatis.annotations.Param;

public interface MstAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MST_ADDRESS
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    int countByExample(MstAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MST_ADDRESS
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    int deleteByExample(MstAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MST_ADDRESS
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    int insert(MstAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MST_ADDRESS
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    int insertSelective(MstAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MST_ADDRESS
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    List<MstAddress> selectByExample(MstAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MST_ADDRESS
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    int updateByExampleSelective(@Param("record") MstAddress record, @Param("example") MstAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MST_ADDRESS
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    int updateByExample(@Param("record") MstAddress record, @Param("example") MstAddressExample example);
}