package jp.tokyo.higashimurayama.tohnaman.batch.mybatis.model;

public class MstAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MST_ADDRESS.ID
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MST_ADDRESS.ZIP
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    private String zip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MST_ADDRESS.OFFICE_FLG
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    private Integer officeFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MST_ADDRESS.DELETE_FLG
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    private Integer deleteFlg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MST_ADDRESS.PREF_NAME
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    private String prefName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MST_ADDRESS.PREF_KANA
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    private String prefKana;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MST_ADDRESS.CITY_NAME
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MST_ADDRESS.CITY_KANA
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    private String cityKana;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MST_ADDRESS.TOWN_NAME
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    private String townName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MST_ADDRESS.TOWN_KANA
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    private String townKana;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MST_ADDRESS.TOWN_MEMO
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    private String townMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MST_ADDRESS.AZA_NAME
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    private String azaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MST_ADDRESS.AZA_KANA
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    private String azaKana;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MST_ADDRESS.MEMO
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MST_ADDRESS.OFFICE_NAME
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    private String officeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MST_ADDRESS.OFFICE_KANA
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    private String officeKana;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MST_ADDRESS.OFFICE_ADDRESS
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    private String officeAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MST_ADDRESS.NEW_ID
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    private String newId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MST_ADDRESS.REGIST_DATE
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    private String registDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MST_ADDRESS.ID
     *
     * @return the value of MST_ADDRESS.ID
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MST_ADDRESS.ID
     *
     * @param id the value for MST_ADDRESS.ID
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MST_ADDRESS.ZIP
     *
     * @return the value of MST_ADDRESS.ZIP
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MST_ADDRESS.ZIP
     *
     * @param zip the value for MST_ADDRESS.ZIP
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public void setZip(String zip) {
        this.zip = zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MST_ADDRESS.OFFICE_FLG
     *
     * @return the value of MST_ADDRESS.OFFICE_FLG
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public Integer getOfficeFlg() {
        return officeFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MST_ADDRESS.OFFICE_FLG
     *
     * @param officeFlg the value for MST_ADDRESS.OFFICE_FLG
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public void setOfficeFlg(Integer officeFlg) {
        this.officeFlg = officeFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MST_ADDRESS.DELETE_FLG
     *
     * @return the value of MST_ADDRESS.DELETE_FLG
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public Integer getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MST_ADDRESS.DELETE_FLG
     *
     * @param deleteFlg the value for MST_ADDRESS.DELETE_FLG
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public void setDeleteFlg(Integer deleteFlg) {
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MST_ADDRESS.PREF_NAME
     *
     * @return the value of MST_ADDRESS.PREF_NAME
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public String getPrefName() {
        return prefName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MST_ADDRESS.PREF_NAME
     *
     * @param prefName the value for MST_ADDRESS.PREF_NAME
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public void setPrefName(String prefName) {
        this.prefName = prefName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MST_ADDRESS.PREF_KANA
     *
     * @return the value of MST_ADDRESS.PREF_KANA
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public String getPrefKana() {
        return prefKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MST_ADDRESS.PREF_KANA
     *
     * @param prefKana the value for MST_ADDRESS.PREF_KANA
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public void setPrefKana(String prefKana) {
        this.prefKana = prefKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MST_ADDRESS.CITY_NAME
     *
     * @return the value of MST_ADDRESS.CITY_NAME
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MST_ADDRESS.CITY_NAME
     *
     * @param cityName the value for MST_ADDRESS.CITY_NAME
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MST_ADDRESS.CITY_KANA
     *
     * @return the value of MST_ADDRESS.CITY_KANA
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public String getCityKana() {
        return cityKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MST_ADDRESS.CITY_KANA
     *
     * @param cityKana the value for MST_ADDRESS.CITY_KANA
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public void setCityKana(String cityKana) {
        this.cityKana = cityKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MST_ADDRESS.TOWN_NAME
     *
     * @return the value of MST_ADDRESS.TOWN_NAME
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public String getTownName() {
        return townName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MST_ADDRESS.TOWN_NAME
     *
     * @param townName the value for MST_ADDRESS.TOWN_NAME
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public void setTownName(String townName) {
        this.townName = townName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MST_ADDRESS.TOWN_KANA
     *
     * @return the value of MST_ADDRESS.TOWN_KANA
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public String getTownKana() {
        return townKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MST_ADDRESS.TOWN_KANA
     *
     * @param townKana the value for MST_ADDRESS.TOWN_KANA
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public void setTownKana(String townKana) {
        this.townKana = townKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MST_ADDRESS.TOWN_MEMO
     *
     * @return the value of MST_ADDRESS.TOWN_MEMO
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public String getTownMemo() {
        return townMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MST_ADDRESS.TOWN_MEMO
     *
     * @param townMemo the value for MST_ADDRESS.TOWN_MEMO
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public void setTownMemo(String townMemo) {
        this.townMemo = townMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MST_ADDRESS.AZA_NAME
     *
     * @return the value of MST_ADDRESS.AZA_NAME
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public String getAzaName() {
        return azaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MST_ADDRESS.AZA_NAME
     *
     * @param azaName the value for MST_ADDRESS.AZA_NAME
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public void setAzaName(String azaName) {
        this.azaName = azaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MST_ADDRESS.AZA_KANA
     *
     * @return the value of MST_ADDRESS.AZA_KANA
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public String getAzaKana() {
        return azaKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MST_ADDRESS.AZA_KANA
     *
     * @param azaKana the value for MST_ADDRESS.AZA_KANA
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public void setAzaKana(String azaKana) {
        this.azaKana = azaKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MST_ADDRESS.MEMO
     *
     * @return the value of MST_ADDRESS.MEMO
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MST_ADDRESS.MEMO
     *
     * @param memo the value for MST_ADDRESS.MEMO
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public void setMemo(String memo) {
        this.memo = memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MST_ADDRESS.OFFICE_NAME
     *
     * @return the value of MST_ADDRESS.OFFICE_NAME
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public String getOfficeName() {
        return officeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MST_ADDRESS.OFFICE_NAME
     *
     * @param officeName the value for MST_ADDRESS.OFFICE_NAME
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public void setOfficeName(String officeName) {
        this.officeName = officeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MST_ADDRESS.OFFICE_KANA
     *
     * @return the value of MST_ADDRESS.OFFICE_KANA
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public String getOfficeKana() {
        return officeKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MST_ADDRESS.OFFICE_KANA
     *
     * @param officeKana the value for MST_ADDRESS.OFFICE_KANA
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public void setOfficeKana(String officeKana) {
        this.officeKana = officeKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MST_ADDRESS.OFFICE_ADDRESS
     *
     * @return the value of MST_ADDRESS.OFFICE_ADDRESS
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public String getOfficeAddress() {
        return officeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MST_ADDRESS.OFFICE_ADDRESS
     *
     * @param officeAddress the value for MST_ADDRESS.OFFICE_ADDRESS
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public void setOfficeAddress(String officeAddress) {
        this.officeAddress = officeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MST_ADDRESS.NEW_ID
     *
     * @return the value of MST_ADDRESS.NEW_ID
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public String getNewId() {
        return newId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MST_ADDRESS.NEW_ID
     *
     * @param newId the value for MST_ADDRESS.NEW_ID
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public void setNewId(String newId) {
        this.newId = newId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MST_ADDRESS.REGIST_DATE
     *
     * @return the value of MST_ADDRESS.REGIST_DATE
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public String getRegistDate() {
        return registDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MST_ADDRESS.REGIST_DATE
     *
     * @param registDate the value for MST_ADDRESS.REGIST_DATE
     *
     * @mbggenerated Sat Nov 19 19:31:01 JST 2016
     */
    public void setRegistDate(String registDate) {
        this.registDate = registDate;
    }
}