package jp.tokyo.higashimurayama.tohnaman.batch.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class MstAddressExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MST_ADDRESS
     *
     * @mbggenerated Sat Nov 19 19:31:00 JST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MST_ADDRESS
     *
     * @mbggenerated Sat Nov 19 19:31:00 JST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MST_ADDRESS
     *
     * @mbggenerated Sat Nov 19 19:31:00 JST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MST_ADDRESS
     *
     * @mbggenerated Sat Nov 19 19:31:00 JST 2016
     */
    public MstAddressExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MST_ADDRESS
     *
     * @mbggenerated Sat Nov 19 19:31:00 JST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MST_ADDRESS
     *
     * @mbggenerated Sat Nov 19 19:31:00 JST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MST_ADDRESS
     *
     * @mbggenerated Sat Nov 19 19:31:00 JST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MST_ADDRESS
     *
     * @mbggenerated Sat Nov 19 19:31:00 JST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MST_ADDRESS
     *
     * @mbggenerated Sat Nov 19 19:31:00 JST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MST_ADDRESS
     *
     * @mbggenerated Sat Nov 19 19:31:00 JST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MST_ADDRESS
     *
     * @mbggenerated Sat Nov 19 19:31:00 JST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MST_ADDRESS
     *
     * @mbggenerated Sat Nov 19 19:31:00 JST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MST_ADDRESS
     *
     * @mbggenerated Sat Nov 19 19:31:00 JST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MST_ADDRESS
     *
     * @mbggenerated Sat Nov 19 19:31:00 JST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MST_ADDRESS
     *
     * @mbggenerated Sat Nov 19 19:31:00 JST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andZipIsNull() {
            addCriterion("ZIP is null");
            return (Criteria) this;
        }

        public Criteria andZipIsNotNull() {
            addCriterion("ZIP is not null");
            return (Criteria) this;
        }

        public Criteria andZipEqualTo(String value) {
            addCriterion("ZIP =", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipNotEqualTo(String value) {
            addCriterion("ZIP <>", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipGreaterThan(String value) {
            addCriterion("ZIP >", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipGreaterThanOrEqualTo(String value) {
            addCriterion("ZIP >=", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipLessThan(String value) {
            addCriterion("ZIP <", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipLessThanOrEqualTo(String value) {
            addCriterion("ZIP <=", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipLike(String value) {
            addCriterion("ZIP like", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipNotLike(String value) {
            addCriterion("ZIP not like", value, "zip");
            return (Criteria) this;
        }

        public Criteria andZipIn(List<String> values) {
            addCriterion("ZIP in", values, "zip");
            return (Criteria) this;
        }

        public Criteria andZipNotIn(List<String> values) {
            addCriterion("ZIP not in", values, "zip");
            return (Criteria) this;
        }

        public Criteria andZipBetween(String value1, String value2) {
            addCriterion("ZIP between", value1, value2, "zip");
            return (Criteria) this;
        }

        public Criteria andZipNotBetween(String value1, String value2) {
            addCriterion("ZIP not between", value1, value2, "zip");
            return (Criteria) this;
        }

        public Criteria andOfficeFlgIsNull() {
            addCriterion("OFFICE_FLG is null");
            return (Criteria) this;
        }

        public Criteria andOfficeFlgIsNotNull() {
            addCriterion("OFFICE_FLG is not null");
            return (Criteria) this;
        }

        public Criteria andOfficeFlgEqualTo(Integer value) {
            addCriterion("OFFICE_FLG =", value, "officeFlg");
            return (Criteria) this;
        }

        public Criteria andOfficeFlgNotEqualTo(Integer value) {
            addCriterion("OFFICE_FLG <>", value, "officeFlg");
            return (Criteria) this;
        }

        public Criteria andOfficeFlgGreaterThan(Integer value) {
            addCriterion("OFFICE_FLG >", value, "officeFlg");
            return (Criteria) this;
        }

        public Criteria andOfficeFlgGreaterThanOrEqualTo(Integer value) {
            addCriterion("OFFICE_FLG >=", value, "officeFlg");
            return (Criteria) this;
        }

        public Criteria andOfficeFlgLessThan(Integer value) {
            addCriterion("OFFICE_FLG <", value, "officeFlg");
            return (Criteria) this;
        }

        public Criteria andOfficeFlgLessThanOrEqualTo(Integer value) {
            addCriterion("OFFICE_FLG <=", value, "officeFlg");
            return (Criteria) this;
        }

        public Criteria andOfficeFlgIn(List<Integer> values) {
            addCriterion("OFFICE_FLG in", values, "officeFlg");
            return (Criteria) this;
        }

        public Criteria andOfficeFlgNotIn(List<Integer> values) {
            addCriterion("OFFICE_FLG not in", values, "officeFlg");
            return (Criteria) this;
        }

        public Criteria andOfficeFlgBetween(Integer value1, Integer value2) {
            addCriterion("OFFICE_FLG between", value1, value2, "officeFlg");
            return (Criteria) this;
        }

        public Criteria andOfficeFlgNotBetween(Integer value1, Integer value2) {
            addCriterion("OFFICE_FLG not between", value1, value2, "officeFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIsNull() {
            addCriterion("DELETE_FLG is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIsNotNull() {
            addCriterion("DELETE_FLG is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgEqualTo(Integer value) {
            addCriterion("DELETE_FLG =", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotEqualTo(Integer value) {
            addCriterion("DELETE_FLG <>", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgGreaterThan(Integer value) {
            addCriterion("DELETE_FLG >", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgGreaterThanOrEqualTo(Integer value) {
            addCriterion("DELETE_FLG >=", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLessThan(Integer value) {
            addCriterion("DELETE_FLG <", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgLessThanOrEqualTo(Integer value) {
            addCriterion("DELETE_FLG <=", value, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgIn(List<Integer> values) {
            addCriterion("DELETE_FLG in", values, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotIn(List<Integer> values) {
            addCriterion("DELETE_FLG not in", values, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgBetween(Integer value1, Integer value2) {
            addCriterion("DELETE_FLG between", value1, value2, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andDeleteFlgNotBetween(Integer value1, Integer value2) {
            addCriterion("DELETE_FLG not between", value1, value2, "deleteFlg");
            return (Criteria) this;
        }

        public Criteria andPrefNameIsNull() {
            addCriterion("PREF_NAME is null");
            return (Criteria) this;
        }

        public Criteria andPrefNameIsNotNull() {
            addCriterion("PREF_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andPrefNameEqualTo(String value) {
            addCriterion("PREF_NAME =", value, "prefName");
            return (Criteria) this;
        }

        public Criteria andPrefNameNotEqualTo(String value) {
            addCriterion("PREF_NAME <>", value, "prefName");
            return (Criteria) this;
        }

        public Criteria andPrefNameGreaterThan(String value) {
            addCriterion("PREF_NAME >", value, "prefName");
            return (Criteria) this;
        }

        public Criteria andPrefNameGreaterThanOrEqualTo(String value) {
            addCriterion("PREF_NAME >=", value, "prefName");
            return (Criteria) this;
        }

        public Criteria andPrefNameLessThan(String value) {
            addCriterion("PREF_NAME <", value, "prefName");
            return (Criteria) this;
        }

        public Criteria andPrefNameLessThanOrEqualTo(String value) {
            addCriterion("PREF_NAME <=", value, "prefName");
            return (Criteria) this;
        }

        public Criteria andPrefNameLike(String value) {
            addCriterion("PREF_NAME like", value, "prefName");
            return (Criteria) this;
        }

        public Criteria andPrefNameNotLike(String value) {
            addCriterion("PREF_NAME not like", value, "prefName");
            return (Criteria) this;
        }

        public Criteria andPrefNameIn(List<String> values) {
            addCriterion("PREF_NAME in", values, "prefName");
            return (Criteria) this;
        }

        public Criteria andPrefNameNotIn(List<String> values) {
            addCriterion("PREF_NAME not in", values, "prefName");
            return (Criteria) this;
        }

        public Criteria andPrefNameBetween(String value1, String value2) {
            addCriterion("PREF_NAME between", value1, value2, "prefName");
            return (Criteria) this;
        }

        public Criteria andPrefNameNotBetween(String value1, String value2) {
            addCriterion("PREF_NAME not between", value1, value2, "prefName");
            return (Criteria) this;
        }

        public Criteria andPrefKanaIsNull() {
            addCriterion("PREF_KANA is null");
            return (Criteria) this;
        }

        public Criteria andPrefKanaIsNotNull() {
            addCriterion("PREF_KANA is not null");
            return (Criteria) this;
        }

        public Criteria andPrefKanaEqualTo(String value) {
            addCriterion("PREF_KANA =", value, "prefKana");
            return (Criteria) this;
        }

        public Criteria andPrefKanaNotEqualTo(String value) {
            addCriterion("PREF_KANA <>", value, "prefKana");
            return (Criteria) this;
        }

        public Criteria andPrefKanaGreaterThan(String value) {
            addCriterion("PREF_KANA >", value, "prefKana");
            return (Criteria) this;
        }

        public Criteria andPrefKanaGreaterThanOrEqualTo(String value) {
            addCriterion("PREF_KANA >=", value, "prefKana");
            return (Criteria) this;
        }

        public Criteria andPrefKanaLessThan(String value) {
            addCriterion("PREF_KANA <", value, "prefKana");
            return (Criteria) this;
        }

        public Criteria andPrefKanaLessThanOrEqualTo(String value) {
            addCriterion("PREF_KANA <=", value, "prefKana");
            return (Criteria) this;
        }

        public Criteria andPrefKanaLike(String value) {
            addCriterion("PREF_KANA like", value, "prefKana");
            return (Criteria) this;
        }

        public Criteria andPrefKanaNotLike(String value) {
            addCriterion("PREF_KANA not like", value, "prefKana");
            return (Criteria) this;
        }

        public Criteria andPrefKanaIn(List<String> values) {
            addCriterion("PREF_KANA in", values, "prefKana");
            return (Criteria) this;
        }

        public Criteria andPrefKanaNotIn(List<String> values) {
            addCriterion("PREF_KANA not in", values, "prefKana");
            return (Criteria) this;
        }

        public Criteria andPrefKanaBetween(String value1, String value2) {
            addCriterion("PREF_KANA between", value1, value2, "prefKana");
            return (Criteria) this;
        }

        public Criteria andPrefKanaNotBetween(String value1, String value2) {
            addCriterion("PREF_KANA not between", value1, value2, "prefKana");
            return (Criteria) this;
        }

        public Criteria andCityNameIsNull() {
            addCriterion("CITY_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCityNameIsNotNull() {
            addCriterion("CITY_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCityNameEqualTo(String value) {
            addCriterion("CITY_NAME =", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotEqualTo(String value) {
            addCriterion("CITY_NAME <>", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameGreaterThan(String value) {
            addCriterion("CITY_NAME >", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameGreaterThanOrEqualTo(String value) {
            addCriterion("CITY_NAME >=", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLessThan(String value) {
            addCriterion("CITY_NAME <", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLessThanOrEqualTo(String value) {
            addCriterion("CITY_NAME <=", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLike(String value) {
            addCriterion("CITY_NAME like", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotLike(String value) {
            addCriterion("CITY_NAME not like", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameIn(List<String> values) {
            addCriterion("CITY_NAME in", values, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotIn(List<String> values) {
            addCriterion("CITY_NAME not in", values, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameBetween(String value1, String value2) {
            addCriterion("CITY_NAME between", value1, value2, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotBetween(String value1, String value2) {
            addCriterion("CITY_NAME not between", value1, value2, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityKanaIsNull() {
            addCriterion("CITY_KANA is null");
            return (Criteria) this;
        }

        public Criteria andCityKanaIsNotNull() {
            addCriterion("CITY_KANA is not null");
            return (Criteria) this;
        }

        public Criteria andCityKanaEqualTo(String value) {
            addCriterion("CITY_KANA =", value, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaNotEqualTo(String value) {
            addCriterion("CITY_KANA <>", value, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaGreaterThan(String value) {
            addCriterion("CITY_KANA >", value, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaGreaterThanOrEqualTo(String value) {
            addCriterion("CITY_KANA >=", value, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaLessThan(String value) {
            addCriterion("CITY_KANA <", value, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaLessThanOrEqualTo(String value) {
            addCriterion("CITY_KANA <=", value, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaLike(String value) {
            addCriterion("CITY_KANA like", value, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaNotLike(String value) {
            addCriterion("CITY_KANA not like", value, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaIn(List<String> values) {
            addCriterion("CITY_KANA in", values, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaNotIn(List<String> values) {
            addCriterion("CITY_KANA not in", values, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaBetween(String value1, String value2) {
            addCriterion("CITY_KANA between", value1, value2, "cityKana");
            return (Criteria) this;
        }

        public Criteria andCityKanaNotBetween(String value1, String value2) {
            addCriterion("CITY_KANA not between", value1, value2, "cityKana");
            return (Criteria) this;
        }

        public Criteria andTownNameIsNull() {
            addCriterion("TOWN_NAME is null");
            return (Criteria) this;
        }

        public Criteria andTownNameIsNotNull() {
            addCriterion("TOWN_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andTownNameEqualTo(String value) {
            addCriterion("TOWN_NAME =", value, "townName");
            return (Criteria) this;
        }

        public Criteria andTownNameNotEqualTo(String value) {
            addCriterion("TOWN_NAME <>", value, "townName");
            return (Criteria) this;
        }

        public Criteria andTownNameGreaterThan(String value) {
            addCriterion("TOWN_NAME >", value, "townName");
            return (Criteria) this;
        }

        public Criteria andTownNameGreaterThanOrEqualTo(String value) {
            addCriterion("TOWN_NAME >=", value, "townName");
            return (Criteria) this;
        }

        public Criteria andTownNameLessThan(String value) {
            addCriterion("TOWN_NAME <", value, "townName");
            return (Criteria) this;
        }

        public Criteria andTownNameLessThanOrEqualTo(String value) {
            addCriterion("TOWN_NAME <=", value, "townName");
            return (Criteria) this;
        }

        public Criteria andTownNameLike(String value) {
            addCriterion("TOWN_NAME like", value, "townName");
            return (Criteria) this;
        }

        public Criteria andTownNameNotLike(String value) {
            addCriterion("TOWN_NAME not like", value, "townName");
            return (Criteria) this;
        }

        public Criteria andTownNameIn(List<String> values) {
            addCriterion("TOWN_NAME in", values, "townName");
            return (Criteria) this;
        }

        public Criteria andTownNameNotIn(List<String> values) {
            addCriterion("TOWN_NAME not in", values, "townName");
            return (Criteria) this;
        }

        public Criteria andTownNameBetween(String value1, String value2) {
            addCriterion("TOWN_NAME between", value1, value2, "townName");
            return (Criteria) this;
        }

        public Criteria andTownNameNotBetween(String value1, String value2) {
            addCriterion("TOWN_NAME not between", value1, value2, "townName");
            return (Criteria) this;
        }

        public Criteria andTownKanaIsNull() {
            addCriterion("TOWN_KANA is null");
            return (Criteria) this;
        }

        public Criteria andTownKanaIsNotNull() {
            addCriterion("TOWN_KANA is not null");
            return (Criteria) this;
        }

        public Criteria andTownKanaEqualTo(String value) {
            addCriterion("TOWN_KANA =", value, "townKana");
            return (Criteria) this;
        }

        public Criteria andTownKanaNotEqualTo(String value) {
            addCriterion("TOWN_KANA <>", value, "townKana");
            return (Criteria) this;
        }

        public Criteria andTownKanaGreaterThan(String value) {
            addCriterion("TOWN_KANA >", value, "townKana");
            return (Criteria) this;
        }

        public Criteria andTownKanaGreaterThanOrEqualTo(String value) {
            addCriterion("TOWN_KANA >=", value, "townKana");
            return (Criteria) this;
        }

        public Criteria andTownKanaLessThan(String value) {
            addCriterion("TOWN_KANA <", value, "townKana");
            return (Criteria) this;
        }

        public Criteria andTownKanaLessThanOrEqualTo(String value) {
            addCriterion("TOWN_KANA <=", value, "townKana");
            return (Criteria) this;
        }

        public Criteria andTownKanaLike(String value) {
            addCriterion("TOWN_KANA like", value, "townKana");
            return (Criteria) this;
        }

        public Criteria andTownKanaNotLike(String value) {
            addCriterion("TOWN_KANA not like", value, "townKana");
            return (Criteria) this;
        }

        public Criteria andTownKanaIn(List<String> values) {
            addCriterion("TOWN_KANA in", values, "townKana");
            return (Criteria) this;
        }

        public Criteria andTownKanaNotIn(List<String> values) {
            addCriterion("TOWN_KANA not in", values, "townKana");
            return (Criteria) this;
        }

        public Criteria andTownKanaBetween(String value1, String value2) {
            addCriterion("TOWN_KANA between", value1, value2, "townKana");
            return (Criteria) this;
        }

        public Criteria andTownKanaNotBetween(String value1, String value2) {
            addCriterion("TOWN_KANA not between", value1, value2, "townKana");
            return (Criteria) this;
        }

        public Criteria andTownMemoIsNull() {
            addCriterion("TOWN_MEMO is null");
            return (Criteria) this;
        }

        public Criteria andTownMemoIsNotNull() {
            addCriterion("TOWN_MEMO is not null");
            return (Criteria) this;
        }

        public Criteria andTownMemoEqualTo(String value) {
            addCriterion("TOWN_MEMO =", value, "townMemo");
            return (Criteria) this;
        }

        public Criteria andTownMemoNotEqualTo(String value) {
            addCriterion("TOWN_MEMO <>", value, "townMemo");
            return (Criteria) this;
        }

        public Criteria andTownMemoGreaterThan(String value) {
            addCriterion("TOWN_MEMO >", value, "townMemo");
            return (Criteria) this;
        }

        public Criteria andTownMemoGreaterThanOrEqualTo(String value) {
            addCriterion("TOWN_MEMO >=", value, "townMemo");
            return (Criteria) this;
        }

        public Criteria andTownMemoLessThan(String value) {
            addCriterion("TOWN_MEMO <", value, "townMemo");
            return (Criteria) this;
        }

        public Criteria andTownMemoLessThanOrEqualTo(String value) {
            addCriterion("TOWN_MEMO <=", value, "townMemo");
            return (Criteria) this;
        }

        public Criteria andTownMemoLike(String value) {
            addCriterion("TOWN_MEMO like", value, "townMemo");
            return (Criteria) this;
        }

        public Criteria andTownMemoNotLike(String value) {
            addCriterion("TOWN_MEMO not like", value, "townMemo");
            return (Criteria) this;
        }

        public Criteria andTownMemoIn(List<String> values) {
            addCriterion("TOWN_MEMO in", values, "townMemo");
            return (Criteria) this;
        }

        public Criteria andTownMemoNotIn(List<String> values) {
            addCriterion("TOWN_MEMO not in", values, "townMemo");
            return (Criteria) this;
        }

        public Criteria andTownMemoBetween(String value1, String value2) {
            addCriterion("TOWN_MEMO between", value1, value2, "townMemo");
            return (Criteria) this;
        }

        public Criteria andTownMemoNotBetween(String value1, String value2) {
            addCriterion("TOWN_MEMO not between", value1, value2, "townMemo");
            return (Criteria) this;
        }

        public Criteria andAzaNameIsNull() {
            addCriterion("AZA_NAME is null");
            return (Criteria) this;
        }

        public Criteria andAzaNameIsNotNull() {
            addCriterion("AZA_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andAzaNameEqualTo(String value) {
            addCriterion("AZA_NAME =", value, "azaName");
            return (Criteria) this;
        }

        public Criteria andAzaNameNotEqualTo(String value) {
            addCriterion("AZA_NAME <>", value, "azaName");
            return (Criteria) this;
        }

        public Criteria andAzaNameGreaterThan(String value) {
            addCriterion("AZA_NAME >", value, "azaName");
            return (Criteria) this;
        }

        public Criteria andAzaNameGreaterThanOrEqualTo(String value) {
            addCriterion("AZA_NAME >=", value, "azaName");
            return (Criteria) this;
        }

        public Criteria andAzaNameLessThan(String value) {
            addCriterion("AZA_NAME <", value, "azaName");
            return (Criteria) this;
        }

        public Criteria andAzaNameLessThanOrEqualTo(String value) {
            addCriterion("AZA_NAME <=", value, "azaName");
            return (Criteria) this;
        }

        public Criteria andAzaNameLike(String value) {
            addCriterion("AZA_NAME like", value, "azaName");
            return (Criteria) this;
        }

        public Criteria andAzaNameNotLike(String value) {
            addCriterion("AZA_NAME not like", value, "azaName");
            return (Criteria) this;
        }

        public Criteria andAzaNameIn(List<String> values) {
            addCriterion("AZA_NAME in", values, "azaName");
            return (Criteria) this;
        }

        public Criteria andAzaNameNotIn(List<String> values) {
            addCriterion("AZA_NAME not in", values, "azaName");
            return (Criteria) this;
        }

        public Criteria andAzaNameBetween(String value1, String value2) {
            addCriterion("AZA_NAME between", value1, value2, "azaName");
            return (Criteria) this;
        }

        public Criteria andAzaNameNotBetween(String value1, String value2) {
            addCriterion("AZA_NAME not between", value1, value2, "azaName");
            return (Criteria) this;
        }

        public Criteria andAzaKanaIsNull() {
            addCriterion("AZA_KANA is null");
            return (Criteria) this;
        }

        public Criteria andAzaKanaIsNotNull() {
            addCriterion("AZA_KANA is not null");
            return (Criteria) this;
        }

        public Criteria andAzaKanaEqualTo(String value) {
            addCriterion("AZA_KANA =", value, "azaKana");
            return (Criteria) this;
        }

        public Criteria andAzaKanaNotEqualTo(String value) {
            addCriterion("AZA_KANA <>", value, "azaKana");
            return (Criteria) this;
        }

        public Criteria andAzaKanaGreaterThan(String value) {
            addCriterion("AZA_KANA >", value, "azaKana");
            return (Criteria) this;
        }

        public Criteria andAzaKanaGreaterThanOrEqualTo(String value) {
            addCriterion("AZA_KANA >=", value, "azaKana");
            return (Criteria) this;
        }

        public Criteria andAzaKanaLessThan(String value) {
            addCriterion("AZA_KANA <", value, "azaKana");
            return (Criteria) this;
        }

        public Criteria andAzaKanaLessThanOrEqualTo(String value) {
            addCriterion("AZA_KANA <=", value, "azaKana");
            return (Criteria) this;
        }

        public Criteria andAzaKanaLike(String value) {
            addCriterion("AZA_KANA like", value, "azaKana");
            return (Criteria) this;
        }

        public Criteria andAzaKanaNotLike(String value) {
            addCriterion("AZA_KANA not like", value, "azaKana");
            return (Criteria) this;
        }

        public Criteria andAzaKanaIn(List<String> values) {
            addCriterion("AZA_KANA in", values, "azaKana");
            return (Criteria) this;
        }

        public Criteria andAzaKanaNotIn(List<String> values) {
            addCriterion("AZA_KANA not in", values, "azaKana");
            return (Criteria) this;
        }

        public Criteria andAzaKanaBetween(String value1, String value2) {
            addCriterion("AZA_KANA between", value1, value2, "azaKana");
            return (Criteria) this;
        }

        public Criteria andAzaKanaNotBetween(String value1, String value2) {
            addCriterion("AZA_KANA not between", value1, value2, "azaKana");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("MEMO is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("MEMO is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("MEMO =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("MEMO <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("MEMO >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("MEMO >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("MEMO <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("MEMO <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("MEMO like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("MEMO not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("MEMO in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("MEMO not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("MEMO between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("MEMO not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andOfficeNameIsNull() {
            addCriterion("OFFICE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andOfficeNameIsNotNull() {
            addCriterion("OFFICE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andOfficeNameEqualTo(String value) {
            addCriterion("OFFICE_NAME =", value, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameNotEqualTo(String value) {
            addCriterion("OFFICE_NAME <>", value, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameGreaterThan(String value) {
            addCriterion("OFFICE_NAME >", value, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameGreaterThanOrEqualTo(String value) {
            addCriterion("OFFICE_NAME >=", value, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameLessThan(String value) {
            addCriterion("OFFICE_NAME <", value, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameLessThanOrEqualTo(String value) {
            addCriterion("OFFICE_NAME <=", value, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameLike(String value) {
            addCriterion("OFFICE_NAME like", value, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameNotLike(String value) {
            addCriterion("OFFICE_NAME not like", value, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameIn(List<String> values) {
            addCriterion("OFFICE_NAME in", values, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameNotIn(List<String> values) {
            addCriterion("OFFICE_NAME not in", values, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameBetween(String value1, String value2) {
            addCriterion("OFFICE_NAME between", value1, value2, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeNameNotBetween(String value1, String value2) {
            addCriterion("OFFICE_NAME not between", value1, value2, "officeName");
            return (Criteria) this;
        }

        public Criteria andOfficeKanaIsNull() {
            addCriterion("OFFICE_KANA is null");
            return (Criteria) this;
        }

        public Criteria andOfficeKanaIsNotNull() {
            addCriterion("OFFICE_KANA is not null");
            return (Criteria) this;
        }

        public Criteria andOfficeKanaEqualTo(String value) {
            addCriterion("OFFICE_KANA =", value, "officeKana");
            return (Criteria) this;
        }

        public Criteria andOfficeKanaNotEqualTo(String value) {
            addCriterion("OFFICE_KANA <>", value, "officeKana");
            return (Criteria) this;
        }

        public Criteria andOfficeKanaGreaterThan(String value) {
            addCriterion("OFFICE_KANA >", value, "officeKana");
            return (Criteria) this;
        }

        public Criteria andOfficeKanaGreaterThanOrEqualTo(String value) {
            addCriterion("OFFICE_KANA >=", value, "officeKana");
            return (Criteria) this;
        }

        public Criteria andOfficeKanaLessThan(String value) {
            addCriterion("OFFICE_KANA <", value, "officeKana");
            return (Criteria) this;
        }

        public Criteria andOfficeKanaLessThanOrEqualTo(String value) {
            addCriterion("OFFICE_KANA <=", value, "officeKana");
            return (Criteria) this;
        }

        public Criteria andOfficeKanaLike(String value) {
            addCriterion("OFFICE_KANA like", value, "officeKana");
            return (Criteria) this;
        }

        public Criteria andOfficeKanaNotLike(String value) {
            addCriterion("OFFICE_KANA not like", value, "officeKana");
            return (Criteria) this;
        }

        public Criteria andOfficeKanaIn(List<String> values) {
            addCriterion("OFFICE_KANA in", values, "officeKana");
            return (Criteria) this;
        }

        public Criteria andOfficeKanaNotIn(List<String> values) {
            addCriterion("OFFICE_KANA not in", values, "officeKana");
            return (Criteria) this;
        }

        public Criteria andOfficeKanaBetween(String value1, String value2) {
            addCriterion("OFFICE_KANA between", value1, value2, "officeKana");
            return (Criteria) this;
        }

        public Criteria andOfficeKanaNotBetween(String value1, String value2) {
            addCriterion("OFFICE_KANA not between", value1, value2, "officeKana");
            return (Criteria) this;
        }

        public Criteria andOfficeAddressIsNull() {
            addCriterion("OFFICE_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andOfficeAddressIsNotNull() {
            addCriterion("OFFICE_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andOfficeAddressEqualTo(String value) {
            addCriterion("OFFICE_ADDRESS =", value, "officeAddress");
            return (Criteria) this;
        }

        public Criteria andOfficeAddressNotEqualTo(String value) {
            addCriterion("OFFICE_ADDRESS <>", value, "officeAddress");
            return (Criteria) this;
        }

        public Criteria andOfficeAddressGreaterThan(String value) {
            addCriterion("OFFICE_ADDRESS >", value, "officeAddress");
            return (Criteria) this;
        }

        public Criteria andOfficeAddressGreaterThanOrEqualTo(String value) {
            addCriterion("OFFICE_ADDRESS >=", value, "officeAddress");
            return (Criteria) this;
        }

        public Criteria andOfficeAddressLessThan(String value) {
            addCriterion("OFFICE_ADDRESS <", value, "officeAddress");
            return (Criteria) this;
        }

        public Criteria andOfficeAddressLessThanOrEqualTo(String value) {
            addCriterion("OFFICE_ADDRESS <=", value, "officeAddress");
            return (Criteria) this;
        }

        public Criteria andOfficeAddressLike(String value) {
            addCriterion("OFFICE_ADDRESS like", value, "officeAddress");
            return (Criteria) this;
        }

        public Criteria andOfficeAddressNotLike(String value) {
            addCriterion("OFFICE_ADDRESS not like", value, "officeAddress");
            return (Criteria) this;
        }

        public Criteria andOfficeAddressIn(List<String> values) {
            addCriterion("OFFICE_ADDRESS in", values, "officeAddress");
            return (Criteria) this;
        }

        public Criteria andOfficeAddressNotIn(List<String> values) {
            addCriterion("OFFICE_ADDRESS not in", values, "officeAddress");
            return (Criteria) this;
        }

        public Criteria andOfficeAddressBetween(String value1, String value2) {
            addCriterion("OFFICE_ADDRESS between", value1, value2, "officeAddress");
            return (Criteria) this;
        }

        public Criteria andOfficeAddressNotBetween(String value1, String value2) {
            addCriterion("OFFICE_ADDRESS not between", value1, value2, "officeAddress");
            return (Criteria) this;
        }

        public Criteria andNewIdIsNull() {
            addCriterion("NEW_ID is null");
            return (Criteria) this;
        }

        public Criteria andNewIdIsNotNull() {
            addCriterion("NEW_ID is not null");
            return (Criteria) this;
        }

        public Criteria andNewIdEqualTo(String value) {
            addCriterion("NEW_ID =", value, "newId");
            return (Criteria) this;
        }

        public Criteria andNewIdNotEqualTo(String value) {
            addCriterion("NEW_ID <>", value, "newId");
            return (Criteria) this;
        }

        public Criteria andNewIdGreaterThan(String value) {
            addCriterion("NEW_ID >", value, "newId");
            return (Criteria) this;
        }

        public Criteria andNewIdGreaterThanOrEqualTo(String value) {
            addCriterion("NEW_ID >=", value, "newId");
            return (Criteria) this;
        }

        public Criteria andNewIdLessThan(String value) {
            addCriterion("NEW_ID <", value, "newId");
            return (Criteria) this;
        }

        public Criteria andNewIdLessThanOrEqualTo(String value) {
            addCriterion("NEW_ID <=", value, "newId");
            return (Criteria) this;
        }

        public Criteria andNewIdLike(String value) {
            addCriterion("NEW_ID like", value, "newId");
            return (Criteria) this;
        }

        public Criteria andNewIdNotLike(String value) {
            addCriterion("NEW_ID not like", value, "newId");
            return (Criteria) this;
        }

        public Criteria andNewIdIn(List<String> values) {
            addCriterion("NEW_ID in", values, "newId");
            return (Criteria) this;
        }

        public Criteria andNewIdNotIn(List<String> values) {
            addCriterion("NEW_ID not in", values, "newId");
            return (Criteria) this;
        }

        public Criteria andNewIdBetween(String value1, String value2) {
            addCriterion("NEW_ID between", value1, value2, "newId");
            return (Criteria) this;
        }

        public Criteria andNewIdNotBetween(String value1, String value2) {
            addCriterion("NEW_ID not between", value1, value2, "newId");
            return (Criteria) this;
        }

        public Criteria andRegistDateIsNull() {
            addCriterion("REGIST_DATE is null");
            return (Criteria) this;
        }

        public Criteria andRegistDateIsNotNull() {
            addCriterion("REGIST_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andRegistDateEqualTo(String value) {
            addCriterion("REGIST_DATE =", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateNotEqualTo(String value) {
            addCriterion("REGIST_DATE <>", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateGreaterThan(String value) {
            addCriterion("REGIST_DATE >", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateGreaterThanOrEqualTo(String value) {
            addCriterion("REGIST_DATE >=", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateLessThan(String value) {
            addCriterion("REGIST_DATE <", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateLessThanOrEqualTo(String value) {
            addCriterion("REGIST_DATE <=", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateLike(String value) {
            addCriterion("REGIST_DATE like", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateNotLike(String value) {
            addCriterion("REGIST_DATE not like", value, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateIn(List<String> values) {
            addCriterion("REGIST_DATE in", values, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateNotIn(List<String> values) {
            addCriterion("REGIST_DATE not in", values, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateBetween(String value1, String value2) {
            addCriterion("REGIST_DATE between", value1, value2, "registDate");
            return (Criteria) this;
        }

        public Criteria andRegistDateNotBetween(String value1, String value2) {
            addCriterion("REGIST_DATE not between", value1, value2, "registDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MST_ADDRESS
     *
     * @mbggenerated do_not_delete_during_merge Sat Nov 19 19:31:00 JST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MST_ADDRESS
     *
     * @mbggenerated Sat Nov 19 19:31:00 JST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}